---
title: "Restaurant Inspection Data for a Sample of 100,000 Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(p8105.datasets)
library(tidyverse)
```

```{r}
# Take random sample of 100,000 with random seed
set.seed(2)
rest_inspec_sample <- rest_inspec %>%
  slice_sample(n = 100000)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Proportion of each Grade in each Borough

```{r}
# Get proportion of each grade in each borough
# Summarize peels back the group level from borough and grade to just borough
rest_inspec_sample %>%
  drop_na(boro, grade) %>%
  filter(boro != "Missing") %>%
  group_by(boro, grade) %>%
  summarize(boro_grade_sum = n()) %>%
  mutate(boro_sum = sum(boro_grade_sum)) %>%
  mutate(boro_grade_prop = boro_grade_sum/boro_sum) %>%
  plot_ly(x = ~boro, y = ~boro_grade_prop, name = ~grade, type = "bar") %>%
    layout(xaxis = list(title = "Borough"),
           yaxis = list(title = "Proportion of Each Grade"),
           legend = list(title = list(text = "Grade")))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Total Number of Inspections by Year

```{r}
# Visualize total number of inspections by year
# Use lubridate package to get years from inspection date
rest_inspec_sample %>%
  mutate(inspection_year = lubridate::year(inspection_date)) %>%
  group_by(inspection_year) %>%
  summarize(
    total_inspections = n()
  ) %>%
  filter(inspection_year >= 2013) %>%
  plot_ly(x = ~inspection_year, y = ~total_inspections, type = "scatter",
          mode = "lines") %>%
  layout(xaxis = list(title = "Inspection Year",
                      tickvals = list(2013, 2014, 2015, 2016, 2017), 
                                      tickmode = "array"),
         yaxis = list(title = "Total Number of Inspections"))
```

### Restaurant Score Distribution by Borough

```{r}
# Get the distribution of scores in each borough
rest_inspec_sample %>%
  filter(boro != "Missing") %>%
  plot_ly(x = ~boro, y = ~score, type = "box") %>%
  layout(xaxis = list(title = "Borough"),
         yaxis = list(title = "Restaurant Score"))
```

